spring:
  application:
    name: payment-service
    
server:
  port: 8082
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-uri:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
      
      
      